#:import MenuBar sms.utils.menubar.MenuBar

<Root>:
    sm: sm
    menu_bar: menu_bar
    orientation: 'vertical'
    Label:
        # canvas.before:
        #     BorderImage:
        #     source: ''
        id: title_bar_label
        size_hint_y: .08
        text: 'Student Management System'
        bold: True
        font_size: sp(30)
    MenuBar:
        id: menu_bar
        size_hint_y: .08
    Manager:
        id: sm
