<PageReports>:
    BoxLayout:
        padding: dp(10)

        Label:
            size_hint_x: .6

        BoxLayout:
            orientation: 'vertical'
            size_hint_x: .4
            MenuButton:
                text: "Students\' Update"
                on_press: root.open_student_update_popup()
            MenuButton:
                text:"Level GPA Cards"
                on_press: root.open_gpa_cards_popup()
            Label:
